"""zen_finance_models

Revision ID: 2898dc65dcd1
Revises: 001_initial_schema
Create Date: 2026-03-23 13:51:18.095883

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2898dc65dcd1"
down_revision: Union[str, None] = "001_initial_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "budgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "amount_limit",
            sa.Numeric(precision=12, scale=2),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "category_id",
            "month",
            "year",
            name="uq_budget_user_cat_month_year",
        ),
    )
    op.create_index(
        op.f("ix_budgets_category_id"), "budgets", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.drop_index(op.f("ix_budget_plans_category_id"), table_name="budget_plans")
    op.drop_index(op.f("ix_budget_plans_user_id"), table_name="budget_plans")
    op.drop_table("budget_plans")
    op.add_column("categories", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.add_column("categories", sa.Column("icon", sa.String(length=64), nullable=True))
    op.create_foreign_key(
        None, "categories", "categories", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "transactions",
        sa.Column(
            "currency", sa.String(length=3), server_default="RUB", nullable=False
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "is_recurring",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "transactions",
        sa.Column(
            "entry_type", sa.String(length=32), server_default="manual", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "entry_type")
    op.drop_column("transactions", "is_recurring")
    op.drop_column("transactions", "currency")
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "icon")
    op.drop_column("categories", "parent_id")
    op.create_table(
        "budget_plans",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("month", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "planned_amount",
            sa.NUMERIC(precision=12, scale=2),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("budget_plans_category_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("budget_plans_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("budget_plans_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "category_id",
            "month",
            name=op.f("uq_budget_user_cat_month"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_budget_plans_user_id"), "budget_plans", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_plans_category_id"),
        "budget_plans",
        ["category_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_category_id"), table_name="budgets")
    op.drop_table("budgets")
    # ### end Alembic commands ###
