"""add_performance_indexes

Revision ID: 6825ab5d3032
Revises: be3bb58149d3
Create Date: 2026-03-30 19:29:50.669110

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6825ab5d3032"
down_revision: Union[str, None] = "be3bb58149d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_transaction_user_executed",
        "transactions",
        ["user_id", "executed_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transaction_user_executed", table_name="transactions")
    # ### end Alembic commands ###
