"""add bank_offers table

Revision ID: 87839f63308a
Revises: bb95b3b80349
Create Date: 2026-07-03 17:50:40.948336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87839f63308a'
down_revision: Union[str, None] = 'bb95b3b80349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('color', sa.String(length=16), server_default='#888888', nullable=False),
    sa.Column('partner_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('clicks', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Seed: current hardcoded frontend presets, so the UI is never empty.
    # partner_url stays NULL until real CPA links are configured via admin.
    op.execute(
        """
        INSERT INTO bank_offers (name, rate, color, sort_order) VALUES
          ('Альфа-Банк', 16.00, '#EF3124', 1),
          ('Т-Банк',     15.00, '#FFDD2D', 2),
          ('Сбер',       14.00, '#21A038', 3),
          ('ВТБ',        13.00, '#002882', 4),
          ('Газпромбанк',12.00, '#0071CE', 5)
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_offers')
    # ### end Alembic commands ###
