"""add_telegram_chat_id_to_users

Revision ID: a1b2c3d4e5f6
Revises: efe8619e215d
Create Date: 2026-05-27 14:15:00.000000

Adds BigInteger telegram_chat_id column to the users table.
UNIQUE constraint ensures one Telegram account maps to at most one user.
nullable=True allows existing users to remain unlinked.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "efe8619e215d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "telegram_chat_id",
            sa.BigInteger(),
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        "uq_users_telegram_chat_id",
        "users",
        ["telegram_chat_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_telegram_chat_id", "users", type_="unique")
    op.drop_column("users", "telegram_chat_id")
    # ### end Alembic commands ###
