"""add monthly_income to users

Revision ID: be3bb58149d3
Revises: d05756d8f778
Create Date: 2026-03-29 17:19:51.027144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3bb58149d3'
down_revision: Union[str, None] = 'd05756d8f778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_income')
    # ### end Alembic commands ###
