"""Add authentication and profile fields to users

Revision ID: d05756d8f778
Revises: 2898dc65dcd1
Create Date: 2026-03-29 14:56:02.224557

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d05756d8f778"
down_revision: Union[str, None] = "2898dc65dcd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=False,
            server_default="REPLACE_ME_BY_RESET",
        ),
    )
    op.add_column("users", sa.Column("full_name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    op.drop_column("users", "full_name")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
