"""add_comment_to_transactions

Revision ID: efe8619e215d
Revises: 6825ab5d3032
Create Date: 2026-04-01 19:47:30.042456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efe8619e215d"
down_revision: Union[str, None] = "6825ab5d3032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("comment", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "comment")
    # ### end Alembic commands ###
